# 应用服务 WEB 访问端口
server:
  port: 10010
spring:
  application:
    name: quanyoumall-cart
  redis:
    host: 8.152.219.128
    port: 6379
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  thymeleaf:
    cache: false

logging:
  level:
    com.wzy.quanyoumall: debug
quanyoumall:
  thread:
    core-size: 50
    max-size: 100
    keep-alive-time: 20