server:
  port: 88
spring:
  application:
    name: quanyoumall-gateway
  cloud:
    gateway:
      enabled: true
      routes:
        - id: product_route
          uri: lb://quanyoumall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/?(?<segment>.*), /$\{segment}

        - id: third_party_route
          uri: lb://quanyoumall-third-party
          predicates:
            - Path=/api/thirdParty/**
          filters:
            - RewritePath=/api/thirdParty/?(?<segment>.*), /$\{segment}

        - id: ware_route
          uri: lb://quanyoumall-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/?(?<segment>.*), /$\{segment}

        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/?(?<segment>.*), /renren-fast/$\{segment}
    nacos:
      discovery:
        server-addr: localhost:8848
