# 应用服务 WEB 访问端口
server:
  port: 8086
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username:
        password:
    alicloud:
      access-key:
      secret-key:
      oss:
        endpoint:
        bucket:

