server:
  port: 80

spring:
  application:
    name: quanyoumall-search
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  thymeleaf:
    cache: false
  redis:
    host: 8.152.219.128
    port: 6379
  session:
    store-type: redis